// Code generated by "stringer -type requestType"; DO NOT EDIT.

package network

import "fmt"

const _requestType_name = "takefreereservereleaserepairStartrepairDonecheckfail"

var _requestType_index = [...]uint8{0, 4, 8, 15, 22, 33, 43, 48, 52}

func (i requestType) String() string {
	i -= 1
	if i < 0 || i >= requestType(len(_requestType_index)-1) {
		return fmt.Sprintf("requestType(%d)", i+1)
	}
	return _requestType_name[_requestType_index[i]:_requestType_index[i+1]]
}
